language: python
env:
  - LANG=en_US.UTF-8
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" 
# command to install dependencies
install: 
  - pip install .
  - pip install nose2
  - pip install mongoquery
  - pip install jsonschema
  - pip install jsonpath-ng
  - pip install json-delta
# command to run tests
script: nose2
